const INVALID_DATA_ERROR_CODE = 400;
const UNAUTHENTICATED_ERROR_ERROR_CODE = 401;
const UNAUTHORIZED_ERROR_ERROR_CODE = 403;
const NOT_FOUND_ERROR_CODE = 404;
const CONFLICT_ERROR_ERROR_CODE = 409;
const SERVER_ERROR_ERROR_CODE = 500;

module.exports = {
  INVALID_DATA_ERROR_CODE,
  UNAUTHENTICATED_ERROR_ERROR_CODE,
  UNAUTHORIZED_ERROR_ERROR_CODE,
  NOT_FOUND_ERROR_CODE,
  CONFLICT_ERROR_ERROR_CODE,
  SERVER_ERROR_ERROR_CODE,
};

// message: 'An error has occured on the server'
